version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - echo | mvn --version
      - mvn clean install package
  post_build:
    commands:
      - echo "Entered the post-build phase"
      - mv target/app-0.0.1-SNAPSHOT.jar ./
      - cp clientLibraryConfig-aws-hello-world.json test-cred.json
artifacts:
  files:
    - app-0.0.1-SNAPSHOT.jar
    - .platform/**/*
    - test-cred.json