version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - echo | mvn --version
      - mvn clean install prepare-package war:exploded
  post_build:
    commands:
      - echo "Entered the post-build phase"
      - mv target/deploy/*.jar app.jar
artifacts:
  files:
    - app.jar